---
- hosts: all
  gather_facts: false
  tasks:
    - delegate_to: localhost
      command: ping -c1 "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
      register: ping
      ignore_errors: true

    - set_fact:
        available: "{{ ping.rc == 0 }}"

    - set_fact:
        reachable: false
        admin_user: false

    - setup:
      when: ping.rc == 0

    - set_fact:
        reachable: true
      when: ping.rc == 0

    - name: run sudo -n true
      command: sudo -n true
      register: ss
      ignore_errors: true
      when: ping.rc == 0

    - set_fact:
        admin_user: "{{ ss.rc == 0 }}"
      when: ping.rc == 0

- hosts: localhost
  gather_facts: false
  tasks:
    - name: update host place in inventory file
      command: "python3 up_inv.py {{ hostvars[item].inventory_file }} {{ item }} {{ hostvars[item].available }} {{ hostvars[item].reachable }} {{ hostvars[item].admin_user }}"
      when: hostvars[item].available is defined and hostvars[item].reachable is defined
      loop: "{{ groups.all }}"
      loop_control:
        loop_var: item
