---
- hosts: all
  gather_facts: false
  tasks:
    # Check ping host
    - delegate_to: localhost
      command: ping -c1 "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
      changed_when: false
      tags: ping

    # Check that we can get facts about host
    - setup:
      changed_when: false
      tags: access

    # Check sudo rights
    - name: run sudo -n true
      command: sudo -n true
      changed_when: false
      tags: sudo
